# Site Info
title: jdw9403's Blog
tagline: "jdw9403's Blog"
description: '개인 공부 및 기록을 위한 블로그 입니다.'
baseurl: ""
url: https://jdw9403.github.io
logo: '/public/softener.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0

# About/contact
author:
  name: jdw9403
  description: 개인 공부 및 기록을 위한 블로그 입니다.
  contact:
    email: mailto:jdw9403@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/categories/'
  Categories:
    - '/blog/categories/'
    # - { Categories All: '/blog/categories/' }
    - { AndroidStudio: '/blog/categories/#AndroidStudio' }
    - { DesignPattern: '/blog/categories/#DesignPattern' }
    
  Tags: 
    - '/blog/tags/'

  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/molang_coffee.png
  caption: 안녕하세요. jdw9403입니다.

# Pugl-In
mathjax: true
google_analytics_token: 'UA-112390680-1'
disqus_short_name: 'jdw9403'